### PR TITLE
fetch more pages for long-running queries

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by hantmac** [comment]
@wolfv Thanks for your contribution!  Could you describe the specific problem that you encountered? There already has a generator for long-running queries which will query pages until `next_uri` is None. The code you can check here https://github.com/databendcloud/databend-py/blob/main/databend_py/client.py#L39.

**Review by hantmac — CHANGES_REQUESTED** [review]
Hi, I found the problem. There has a situation: the `data` in the query process may be empty, but the `next_uri` is not empty. So we fetch pages until the next_url is None. You can the the bug-fix in [this pr](https://github.com/databendcloud/databend-py/pull/7)

**Comment by wolfv** [comment]
Sorry I wasn't explaining the issue very well! I have a long running query and I got some empty results. I checked and I can get results after calling the next uri

**Comment by hantmac** [comment]
> 

Yes,  https://github.com/databendcloud/databend-py/pull/7 this pr fix the bug. So I close this pr and  open it anytime if you have any question.

**Pull request closed without merging**
